import "../styles/global.css";
import { ThemeProvider } from "next-themes";
import SimpleNavbar from "@/components/Header/header";
import Head from "next/head";
import { Analytics } from "@vercel/analytics/react";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

export const metadata = {
  title: "Divine Developers | Home",
  description: "Generated by Divine developers",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <ThemeProvider defaultTheme="dark" attribute="class">
          <Head>
            <meta httpEquiv="Content-Language" content="en" />
            <meta name="description" content="" />
            <title>Divine Developers | Home</title>
          </Head>
          <Analytics />
          <body>
            <SimpleNavbar />
            {children}
          </body>
        </ThemeProvider>
      </ClerkProvider>
    </html>
  );
}
