import "../styles/global.css";
import { ThemeProvider } from "next-themes";
import SimpleNavbar from "@/components/Header/header";
import Head from "next/head";
import { Analytics } from "@vercel/analytics/react";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Toaster } from "@/components/ui/toaster";
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { EdgeStoreProvider } from "@/lib/edgestore";

export const metadata = {
  title: "Divine Developers | Home",
  description: "Generated by Divine developers",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <EdgeStoreProvider>
          <ThemeProvider defaultTheme="dark" attribute="class">
            <Head>
              <meta httpEquiv="Content-Language" content="en" />
              <meta name="description" content="" />
              <title>Divine Developers | Home</title>
            </Head>
            <Analytics />
            <SpeedInsights />
            <body>
              <SimpleNavbar />
              {children}
              <Toaster />
            </body>
          </ThemeProvider>
        </EdgeStoreProvider>
      </ClerkProvider>
    </html>
  );
}
